In [11]:
import os
import tensorflow as tf
import numpy as np
import pandas as pd
%matplotlib inline

In [12]:
DATA_DIR='/home/jupyter/data'

### dataset from np array

In [4]:
x = np.random.normal(size=(10,2))
x

array([[-0.2673395 ,  0.8397985 ],
       [ 0.4215114 ,  1.59650183],
       [ 0.32095545, -0.87147807],
       [ 1.68237833, -1.64231524],
       [-0.60458029,  0.23117716],
       [-0.11939795,  0.98115812],
       [-2.58634282, -0.06939115],
       [-0.40390687,  1.44146753],
       [-0.569293  , -1.22308503],
       [ 0.63920614,  0.04912573]])

In [5]:
inp = tf.data.Dataset.from_tensor_slices(x)

In [6]:
b = inp.batch(2).make_one_shot_iterator().get_next()

In [7]:
with tf.Session() as sess:
    _b = sess.run(b)
    _c = sess.run(b)
_b, _c

(array([[-0.2673395 ,  0.8397985 ],
        [ 0.4215114 ,  1.59650183]]), array([[ 0.32095545, -0.87147807],
        [ 1.68237833, -1.64231524]]))

### Dataset from a generator

In [8]:
sequence = np.random.normal(size=(10,2))
def generator():
    for x in sequence:
        yield x

In [9]:
inp = tf.data.Dataset.from_generator(generator, output_types=tf.float64, output_shapes=(tf.TensorShape([2])))
b = inp.batch(2).make_one_shot_iterator().get_next()
with tf.Session() as sess:
    _b = sess.run(b)
    _c = sess.run(b)
_b, _c    

(array([[-1.65911584, -0.319281  ],
        [-0.38373948, -0.34553233]]), array([[-1.55824123,  0.70972351],
        [ 0.33166813,  0.16585409]]))

### Dataset from CSV file
A subset of the famous flight data dataset in Big Query: All flight that departed from Atlanta on any June day between 2006 to 2017

37MB in 403'358 records. That's easy to handle in memory for exploration

In [14]:
atlanta_june = pd.DataFrame.from_csv(os.path.join(DATA_DIR, "atl_june.csv"))

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [15]:
atlanta_june[0:10]

FL_YEAR  FL_MONTH  FL_DOM  FL_DOW UNIQUE_CARRIER  FL_NUM  \
FL_DATE                                                                
2016-06-01     2016         6       1       4             EV    5602   
2016-06-01     2016         6       1       4             DL    2614   
2016-06-01     2016         6       1       4             EV    5071   
2016-06-01     2016         6       1       4             EV    5597   
2016-06-02     2016         6       2       5             EV    5071   
2016-06-02     2016         6       2       5             EV    5597   
2016-06-02     2016         6       2       5             DL    2614   
2016-06-02     2016         6       2       5             EV    5602   
2016-06-03     2016         6       3       6             EV    5071   
2016-06-03     2016         6       3       6             DL    2614   

            ORIGIN_AIRPORT_SEQ_ID  DEST_AIRPORT_SEQ_ID ORIGIN DEST    ...     \
FL_DATE                                                               ...      
2016-06-01                1039705              1295104    ATL  LFT    ...      
2016-06-01                1039705              1295104    ATL  LFT    ...      
2016-06-01                1039705              1295104    ATL  LFT    ...      
2016-06-01                1039705              1295104    ATL  LFT    ...      
2016-06-02                1039705              1295104    ATL  LFT    ...      
2016-06-02                1039705              1295104    ATL  LFT    ...      
2016-06-02                1039705              1295104    ATL  LFT    ...      
2016-06-02                1039705              1295104    ATL  LFT    ...      
2016-06-03                1039705              1295104    ATL  LFT    ...      
2016-06-03                1039705              1295104    ATL  LFT    ...      

            TAXI_OUT  WHEELS_OFF  WHEELS_ON  TAXI_IN  CRS_ARR_TIME  ARR_DELAY  \
FL_DATE                                                                         
2016-06-01        47        1803       1818        5          1705         78   
2016-06-01        20        2028       2039        5          2056        -12   
2016-06-01        21        1429       1445        5          1344         66   
2016-06-01        16        1019       1041        7          1051         -3   
2016-06-02        23        1322       1338       25          1344         19   
2016-06-02        29        1254       1312        6          1051        147   
2016-06-02        24        2029       2039        7          2056        -10   
2016-06-02        25        1646       1654        5          1705         -6   
2016-06-03        18        1344       1406        5          1344         27   
2016-06-03        21        2027       2044        7          2056         -5   

            CANCELLED  CANCELLATION_CODE  DIVERTED  DISTANCE  
FL_DATE                                                       
2016-06-01          0                NaN         0       503  
2016-06-01          0                NaN         0       503  
2016-06-01          0                NaN         0       503  
2016-06-01          0                NaN         0       503  
2016-06-02          0                NaN         0       503  
2016-06-02          0                NaN         0       503  
2016-06-02          0                NaN         0       503  
2016-06-02          0                NaN         0       503  
2016-06-03          0                NaN         0       503  
2016-06-03          0                NaN         0       503  

[10 rows x 22 columns]

In [16]:
atlanta_june.describe()

FL_YEAR  FL_MONTH         FL_DOM         FL_DOW         FL_NUM  \
count  403358.000000  403358.0  403358.000000  403358.000000  403358.000000   
mean     2011.395998       6.0      15.575033       3.958536    2324.654210   
std         3.438737       0.0       8.637871       1.968028    1826.668615   
min      2006.000000       6.0       1.000000       1.000000       1.000000   
25%      2008.000000       6.0       8.000000       2.000000     873.000000   
50%      2011.000000       6.0      16.000000       4.000000    1711.000000   
75%      2014.000000       6.0      23.000000       6.000000    4332.000000   
max      2017.000000       6.0      30.000000       7.000000    7425.000000   

       ORIGIN_AIRPORT_SEQ_ID  DEST_AIRPORT_SEQ_ID   CRS_DEP_TIME  \
count           4.033580e+05         4.033580e+05  403358.000000   
mean            1.039704e+06         1.278804e+06    1460.046948   
std             9.995802e-01         1.519290e+05     463.110599   
min             1.039703e+06         1.013501e+06     500.000000   
25%             1.039703e+06         1.129802e+06    1035.000000   
50%             1.039703e+06         1.294502e+06    1453.000000   
75%             1.039705e+06         1.410001e+06    1856.000000   
max             1.039705e+06         1.591902e+06    2350.000000   

           DEP_DELAY       TAXI_OUT     WHEELS_OFF      WHEELS_ON  \
count  403358.000000  403358.000000  403358.000000  403358.000000   
mean       15.029393      20.590726    1487.350684    1514.163475   
std        39.325740      11.310037     498.089658     538.377473   
min       -54.000000       0.000000       1.000000       1.000000   
25%        -3.000000      14.000000    1051.000000    1128.000000   
50%         0.000000      18.000000    1510.000000    1535.000000   
75%        15.000000      24.000000    1925.000000    1948.000000   
max      1427.000000     226.000000    2400.000000    2400.000000   

             TAXI_IN   CRS_ARR_TIME      ARR_DELAY  CANCELLED  \
count  403358.000000  403358.000000  403358.000000   403358.0   
mean        6.049626    1552.945956      11.898465        0.0   
std         4.550384     499.354124      42.376085        0.0   
min         0.000000       0.000000     -61.000000        0.0   
25%         4.000000    1150.000000     -10.000000        0.0   
50%         5.000000    1557.000000      -1.000000        0.0   
75%         7.000000    1958.000000      16.000000        0.0   
max       230.000000    2359.000000    1444.000000        0.0   

       CANCELLATION_CODE  DIVERTED       DISTANCE  
count                0.0  403358.0  403358.000000  
mean                 NaN       0.0     643.922352  
std                  NaN       0.0     471.523150  
min                  NaN       0.0      79.000000  
25%                  NaN       0.0     356.000000  
50%                  NaN       0.0     547.000000  
75%                  NaN       0.0     743.000000  
max                  NaN       0.0    4502.000000

#### Creating a tf.TextLineDataset

In [17]:
atlanta_june.columns

Index(['FL_YEAR', 'FL_MONTH', 'FL_DOM', 'FL_DOW', 'UNIQUE_CARRIER', 'FL_NUM',
       'ORIGIN_AIRPORT_SEQ_ID', 'DEST_AIRPORT_SEQ_ID', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON',
       'TAXI_IN', 'CRS_ARR_TIME', 'ARR_DELAY', 'CANCELLED',
       'CANCELLATION_CODE', 'DIVERTED', 'DISTANCE'],
      dtype='object')

In [18]:
COLUMNS = ['FL_DATE', 'FL_YEAR', 'FL_MONTH', 'FL_DOM', 'FL_DOW', 'UNIQUE_CARRIER', 'FL_NUM',
       'ORIGIN_AIRPORT_SEQ_ID', 'DEST_AIRPORT_SEQ_ID', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON',
       'TAXI_IN', 'CRS_ARR_TIME', 'ARR_DELAY', 'CANCELLED',
       'CANCELLATION_CODE', 'DIVERTED', 'DISTANCE']
DEFAULTS = [["-"], [], [], [], [], ["-"], ["-"], ["-"], ["-"], ["-"], ["-"], [], [], [], [], [], [], [], [], [], ['NONE'], [], []]

We're not using the easier `tf.contrib.data.make_csv_dataset` API here because it apparently assumes the data is clean already. With the TextLineDataset, we're able to process each row as we see fit and we can set defaults, types and handle erroneous rows. 

In [19]:
SELECT=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
inp = tf.data.TextLineDataset("gs://ingres/atl_june.csv")
def decode_csv(row):
    cols = tf.decode_csv(row, select_cols=SELECT, record_defaults=DEFAULTS)
    features = dict(zip([COLUMNS[i] for i in SELECT], cols))
    return features
inp = inp.skip(1).map(decode_csv).batch(2)

In [20]:
b = inp.make_one_shot_iterator().get_next()

In [21]:
with tf.Session() as sess:
    _b = sess.run(b)
    _c = sess.run(b)
_b, _c    

({'ARR_DELAY': array([ 78., -12.], dtype=float32),
  'CANCELLATION_CODE': array([b'NONE', b'NONE'], dtype=object),
  'CANCELLED': array([0., 0.], dtype=float32),
  'CRS_ARR_TIME': array([1705., 2056.], dtype=float32),
  'CRS_DEP_TIME': array([1621., 2010.], dtype=float32),
  'DEP_DELAY': array([55., -2.], dtype=float32),
  'DEST': array([b'LFT', b'LFT'], dtype=object),
  'DEST_AIRPORT_SEQ_ID': array([b'1295104', b'1295104'], dtype=object),
  'DISTANCE': array([503., 503.], dtype=float32),
  'DIVERTED': array([0., 0.], dtype=float32),
  'FL_DATE': array([b'2016-06-01', b'2016-06-01'], dtype=object),
  'FL_DOM': array([1., 1.], dtype=float32),
  'FL_DOW': array([4., 4.], dtype=float32),
  'FL_MONTH': array([6., 6.], dtype=float32),
  'FL_NUM': array([b'5602', b'2614'], dtype=object),
  'FL_YEAR': array([2016., 2016.], dtype=float32),
  'ORIGIN': array([b'ATL', b'ATL'], dtype=object),
  'ORIGIN_AIRPORT_SEQ_ID': array([b'1039705', b'1039705'], dtype=object),
  'TAXI_IN': array([5., 5.], dt